namespace Password_Manager
{
    partial class frmLoginandRegister
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation1 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmLoginandRegister));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.bunifuPages1 = new Bunifu.UI.WinForms.BunifuPages();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.linkForgotPassword = new System.Windows.Forms.LinkLabel();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.btnLoginAccount = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtLoginPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtLoginAccount = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.btnAccountRegister = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label5 = new System.Windows.Forms.Label();
            this.linkPolicy = new System.Windows.Forms.LinkLabel();
            this.label4 = new System.Windows.Forms.Label();
            this.chkPolicy = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.bunifuSeparator2 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.txtRegisterPhoneNumber = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtConfirmRegisterPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtRegisterPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtRegisterAccount = new Bunifu.UI.WinForms.BunifuTextBox();
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.label6 = new System.Windows.Forms.Label();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.btnRegisterPage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLoginPage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuPages1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.bunifuGradientPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = false;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = false;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // bunifuPages1
            // 
            this.bunifuPages1.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            this.bunifuPages1.AllowTransitions = true;
            this.bunifuPages1.Controls.Add(this.tabPage1);
            this.bunifuPages1.Controls.Add(this.tabPage2);
            this.bunifuPages1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPages1.Location = new System.Drawing.Point(401, 0);
            this.bunifuPages1.Multiline = true;
            this.bunifuPages1.Name = "bunifuPages1";
            this.bunifuPages1.Page = this.tabPage2;
            this.bunifuPages1.PageIndex = 1;
            this.bunifuPages1.PageName = "tabPage2";
            this.bunifuPages1.PageTitle = "đăng ký";
            this.bunifuPages1.SelectedIndex = 0;
            this.bunifuPages1.Size = new System.Drawing.Size(423, 527);
            this.bunifuPages1.TabIndex = 1;
            animation1.AnimateOnlyDifferences = true;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.bunifuPages1.Transition = animation1;
            this.bunifuPages1.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.Scale;
            // 
            // tabPage1
            // 
            this.tabPage1.BackColor = System.Drawing.Color.WhiteSmoke;
            this.tabPage1.Controls.Add(this.linkForgotPassword);
            this.tabPage1.Controls.Add(this.bunifuSeparator1);
            this.tabPage1.Controls.Add(this.btnLoginAccount);
            this.tabPage1.Controls.Add(this.txtLoginPassword);
            this.tabPage1.Controls.Add(this.txtLoginAccount);
            this.tabPage1.Controls.Add(this.label3);
            this.tabPage1.Location = new System.Drawing.Point(4, 4);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(415, 501);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "đăng_nhập";
            // 
            // linkForgotPassword
            // 
            this.linkForgotPassword.AutoSize = true;
            this.linkForgotPassword.Location = new System.Drawing.Point(88, 322);
            this.linkForgotPassword.Name = "linkForgotPassword";
            this.linkForgotPassword.Size = new System.Drawing.Size(86, 13);
            this.linkForgotPassword.TabIndex = 5;
            this.linkForgotPassword.TabStop = true;
            this.linkForgotPassword.Text = "Quên mật khẩu?";
            this.linkForgotPassword.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.linkForgotPassword_LinkClicked);
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator1.LineThickness = 1;
            this.bunifuSeparator1.Location = new System.Drawing.Point(63, 183);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator1.Size = new System.Drawing.Size(299, 15);
            this.bunifuSeparator1.TabIndex = 4;
            // 
            // btnLoginAccount
            // 
            this.btnLoginAccount.AllowAnimations = true;
            this.btnLoginAccount.AllowMouseEffects = true;
            this.btnLoginAccount.AllowToggling = false;
            this.btnLoginAccount.AnimationSpeed = 200;
            this.btnLoginAccount.AutoGenerateColors = false;
            this.btnLoginAccount.AutoRoundBorders = false;
            this.btnLoginAccount.AutoSizeLeftIcon = true;
            this.btnLoginAccount.AutoSizeRightIcon = true;
            this.btnLoginAccount.BackColor = System.Drawing.Color.Transparent;
            this.btnLoginAccount.BackColor1 = System.Drawing.Color.Transparent;
            this.btnLoginAccount.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLoginAccount.BackgroundImage")));
            this.btnLoginAccount.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoginAccount.ButtonText = "Đăng Nhập";
            this.btnLoginAccount.ButtonTextMarginLeft = 0;
            this.btnLoginAccount.ColorContrastOnClick = 45;
            this.btnLoginAccount.ColorContrastOnHover = 45;
            this.btnLoginAccount.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnLoginAccount.CustomizableEdges = borderEdges1;
            this.btnLoginAccount.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLoginAccount.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLoginAccount.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLoginAccount.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLoginAccount.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLoginAccount.Font = new System.Drawing.Font("Arial", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLoginAccount.ForeColor = System.Drawing.Color.SeaGreen;
            this.btnLoginAccount.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLoginAccount.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLoginAccount.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLoginAccount.IconMarginLeft = 11;
            this.btnLoginAccount.IconPadding = 10;
            this.btnLoginAccount.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLoginAccount.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLoginAccount.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLoginAccount.IconSize = 25;
            this.btnLoginAccount.IdleBorderColor = System.Drawing.Color.SeaGreen;
            this.btnLoginAccount.IdleBorderRadius = 35;
            this.btnLoginAccount.IdleBorderThickness = 2;
            this.btnLoginAccount.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnLoginAccount.IdleIconLeftImage = null;
            this.btnLoginAccount.IdleIconRightImage = null;
            this.btnLoginAccount.IndicateFocus = false;
            this.btnLoginAccount.Location = new System.Drawing.Point(134, 354);
            this.btnLoginAccount.Name = "btnLoginAccount";
            this.btnLoginAccount.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLoginAccount.OnDisabledState.BorderRadius = 35;
            this.btnLoginAccount.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoginAccount.OnDisabledState.BorderThickness = 2;
            this.btnLoginAccount.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLoginAccount.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLoginAccount.OnDisabledState.IconLeftImage = null;
            this.btnLoginAccount.OnDisabledState.IconRightImage = null;
            this.btnLoginAccount.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLoginAccount.onHoverState.BorderRadius = 35;
            this.btnLoginAccount.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoginAccount.onHoverState.BorderThickness = 2;
            this.btnLoginAccount.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLoginAccount.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLoginAccount.onHoverState.IconLeftImage = null;
            this.btnLoginAccount.onHoverState.IconRightImage = null;
            this.btnLoginAccount.OnIdleState.BorderColor = System.Drawing.Color.SeaGreen;
            this.btnLoginAccount.OnIdleState.BorderRadius = 35;
            this.btnLoginAccount.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoginAccount.OnIdleState.BorderThickness = 2;
            this.btnLoginAccount.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnLoginAccount.OnIdleState.ForeColor = System.Drawing.Color.SeaGreen;
            this.btnLoginAccount.OnIdleState.IconLeftImage = null;
            this.btnLoginAccount.OnIdleState.IconRightImage = null;
            this.btnLoginAccount.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLoginAccount.OnPressedState.BorderRadius = 35;
            this.btnLoginAccount.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoginAccount.OnPressedState.BorderThickness = 2;
            this.btnLoginAccount.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLoginAccount.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLoginAccount.OnPressedState.IconLeftImage = null;
            this.btnLoginAccount.OnPressedState.IconRightImage = null;
            this.btnLoginAccount.Size = new System.Drawing.Size(159, 46);
            this.btnLoginAccount.TabIndex = 3;
            this.btnLoginAccount.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLoginAccount.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLoginAccount.TextMarginLeft = 0;
            this.btnLoginAccount.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLoginAccount.UseDefaultRadiusAndThickness = true;
            // 
            // txtLoginPassword
            // 
            this.txtLoginPassword.AcceptsReturn = false;
            this.txtLoginPassword.AcceptsTab = false;
            this.txtLoginPassword.AnimationSpeed = 200;
            this.txtLoginPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtLoginPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtLoginPassword.BackColor = System.Drawing.Color.Transparent;
            this.txtLoginPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtLoginPassword.BackgroundImage")));
            this.txtLoginPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtLoginPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtLoginPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtLoginPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtLoginPassword.BorderRadius = 35;
            this.txtLoginPassword.BorderThickness = 1;
            this.txtLoginPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtLoginPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLoginPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtLoginPassword.DefaultText = "";
            this.txtLoginPassword.FillColor = System.Drawing.Color.White;
            this.txtLoginPassword.HideSelection = true;
            this.txtLoginPassword.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtLoginPassword.IconLeft")));
            this.txtLoginPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLoginPassword.IconPadding = 4;
            this.txtLoginPassword.IconRight = null;
            this.txtLoginPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLoginPassword.Lines = new string[0];
            this.txtLoginPassword.Location = new System.Drawing.Point(88, 278);
            this.txtLoginPassword.MaxLength = 32767;
            this.txtLoginPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtLoginPassword.Modified = false;
            this.txtLoginPassword.Multiline = false;
            this.txtLoginPassword.Name = "txtLoginPassword";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLoginPassword.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtLoginPassword.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLoginPassword.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLoginPassword.OnIdleState = stateProperties4;
            this.txtLoginPassword.Padding = new System.Windows.Forms.Padding(3);
            this.txtLoginPassword.PasswordChar = '\0';
            this.txtLoginPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtLoginPassword.PlaceholderText = "Nhập mật khẩu";
            this.txtLoginPassword.ReadOnly = false;
            this.txtLoginPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtLoginPassword.SelectedText = "";
            this.txtLoginPassword.SelectionLength = 0;
            this.txtLoginPassword.SelectionStart = 0;
            this.txtLoginPassword.ShortcutsEnabled = true;
            this.txtLoginPassword.Size = new System.Drawing.Size(260, 37);
            this.txtLoginPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtLoginPassword.TabIndex = 2;
            this.txtLoginPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtLoginPassword.TextMarginBottom = 0;
            this.txtLoginPassword.TextMarginLeft = 3;
            this.txtLoginPassword.TextMarginTop = 0;
            this.txtLoginPassword.TextPlaceholder = "Nhập mật khẩu";
            this.txtLoginPassword.UseSystemPasswordChar = false;
            this.txtLoginPassword.WordWrap = true;
            this.txtLoginPassword.TextChanged += new System.EventHandler(this.txtLoginPassword_TextChanged);
            // 
            // txtLoginAccount
            // 
            this.txtLoginAccount.AcceptsReturn = false;
            this.txtLoginAccount.AcceptsTab = false;
            this.txtLoginAccount.AnimationSpeed = 200;
            this.txtLoginAccount.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtLoginAccount.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtLoginAccount.BackColor = System.Drawing.Color.Transparent;
            this.txtLoginAccount.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtLoginAccount.BackgroundImage")));
            this.txtLoginAccount.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtLoginAccount.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtLoginAccount.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtLoginAccount.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtLoginAccount.BorderRadius = 35;
            this.txtLoginAccount.BorderThickness = 1;
            this.txtLoginAccount.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtLoginAccount.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLoginAccount.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtLoginAccount.DefaultText = "";
            this.txtLoginAccount.FillColor = System.Drawing.Color.White;
            this.txtLoginAccount.HideSelection = true;
            this.txtLoginAccount.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtLoginAccount.IconLeft")));
            this.txtLoginAccount.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLoginAccount.IconPadding = 4;
            this.txtLoginAccount.IconRight = null;
            this.txtLoginAccount.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLoginAccount.Lines = new string[0];
            this.txtLoginAccount.Location = new System.Drawing.Point(88, 222);
            this.txtLoginAccount.MaxLength = 32767;
            this.txtLoginAccount.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtLoginAccount.Modified = false;
            this.txtLoginAccount.Multiline = false;
            this.txtLoginAccount.Name = "txtLoginAccount";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLoginAccount.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtLoginAccount.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLoginAccount.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLoginAccount.OnIdleState = stateProperties8;
            this.txtLoginAccount.Padding = new System.Windows.Forms.Padding(3);
            this.txtLoginAccount.PasswordChar = '\0';
            this.txtLoginAccount.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtLoginAccount.PlaceholderText = "Nhập tài khoản";
            this.txtLoginAccount.ReadOnly = false;
            this.txtLoginAccount.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtLoginAccount.SelectedText = "";
            this.txtLoginAccount.SelectionLength = 0;
            this.txtLoginAccount.SelectionStart = 0;
            this.txtLoginAccount.ShortcutsEnabled = true;
            this.txtLoginAccount.Size = new System.Drawing.Size(260, 37);
            this.txtLoginAccount.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtLoginAccount.TabIndex = 1;
            this.txtLoginAccount.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtLoginAccount.TextMarginBottom = 0;
            this.txtLoginAccount.TextMarginLeft = 3;
            this.txtLoginAccount.TextMarginTop = 0;
            this.txtLoginAccount.TextPlaceholder = "Nhập tài khoản";
            this.txtLoginAccount.UseSystemPasswordChar = false;
            this.txtLoginAccount.WordWrap = true;
            this.txtLoginAccount.TextChanged += new System.EventHandler(this.bunifuTextBox1_TextChanged);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Arial", 21.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(124, 132);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(169, 34);
            this.label3.TabIndex = 0;
            this.label3.Text = "Đăng Nhập";
            // 
            // tabPage2
            // 
            this.tabPage2.BackColor = System.Drawing.Color.WhiteSmoke;
            this.tabPage2.Controls.Add(this.btnAccountRegister);
            this.tabPage2.Controls.Add(this.label5);
            this.tabPage2.Controls.Add(this.linkPolicy);
            this.tabPage2.Controls.Add(this.label4);
            this.tabPage2.Controls.Add(this.chkPolicy);
            this.tabPage2.Controls.Add(this.bunifuSeparator2);
            this.tabPage2.Controls.Add(this.txtRegisterPhoneNumber);
            this.tabPage2.Controls.Add(this.txtConfirmRegisterPassword);
            this.tabPage2.Controls.Add(this.txtRegisterPassword);
            this.tabPage2.Controls.Add(this.txtRegisterAccount);
            this.tabPage2.Location = new System.Drawing.Point(4, 4);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(415, 501);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "đăng ký";
            // 
            // btnAccountRegister
            // 
            this.btnAccountRegister.AllowAnimations = true;
            this.btnAccountRegister.AllowMouseEffects = true;
            this.btnAccountRegister.AllowToggling = false;
            this.btnAccountRegister.AnimationSpeed = 200;
            this.btnAccountRegister.AutoGenerateColors = false;
            this.btnAccountRegister.AutoRoundBorders = false;
            this.btnAccountRegister.AutoSizeLeftIcon = true;
            this.btnAccountRegister.AutoSizeRightIcon = true;
            this.btnAccountRegister.BackColor = System.Drawing.Color.Transparent;
            this.btnAccountRegister.BackColor1 = System.Drawing.Color.Transparent;
            this.btnAccountRegister.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAccountRegister.BackgroundImage")));
            this.btnAccountRegister.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccountRegister.ButtonText = "Đăng Ký";
            this.btnAccountRegister.ButtonTextMarginLeft = 0;
            this.btnAccountRegister.ColorContrastOnClick = 45;
            this.btnAccountRegister.ColorContrastOnHover = 45;
            this.btnAccountRegister.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnAccountRegister.CustomizableEdges = borderEdges2;
            this.btnAccountRegister.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAccountRegister.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAccountRegister.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAccountRegister.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAccountRegister.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAccountRegister.Font = new System.Drawing.Font("Arial", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAccountRegister.ForeColor = System.Drawing.Color.SeaGreen;
            this.btnAccountRegister.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAccountRegister.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAccountRegister.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAccountRegister.IconMarginLeft = 11;
            this.btnAccountRegister.IconPadding = 10;
            this.btnAccountRegister.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAccountRegister.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAccountRegister.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAccountRegister.IconSize = 25;
            this.btnAccountRegister.IdleBorderColor = System.Drawing.Color.SeaGreen;
            this.btnAccountRegister.IdleBorderRadius = 35;
            this.btnAccountRegister.IdleBorderThickness = 2;
            this.btnAccountRegister.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnAccountRegister.IdleIconLeftImage = null;
            this.btnAccountRegister.IdleIconRightImage = null;
            this.btnAccountRegister.IndicateFocus = false;
            this.btnAccountRegister.Location = new System.Drawing.Point(144, 400);
            this.btnAccountRegister.Name = "btnAccountRegister";
            this.btnAccountRegister.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAccountRegister.OnDisabledState.BorderRadius = 35;
            this.btnAccountRegister.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccountRegister.OnDisabledState.BorderThickness = 2;
            this.btnAccountRegister.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAccountRegister.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAccountRegister.OnDisabledState.IconLeftImage = null;
            this.btnAccountRegister.OnDisabledState.IconRightImage = null;
            this.btnAccountRegister.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAccountRegister.onHoverState.BorderRadius = 35;
            this.btnAccountRegister.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccountRegister.onHoverState.BorderThickness = 2;
            this.btnAccountRegister.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAccountRegister.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAccountRegister.onHoverState.IconLeftImage = null;
            this.btnAccountRegister.onHoverState.IconRightImage = null;
            this.btnAccountRegister.OnIdleState.BorderColor = System.Drawing.Color.SeaGreen;
            this.btnAccountRegister.OnIdleState.BorderRadius = 35;
            this.btnAccountRegister.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccountRegister.OnIdleState.BorderThickness = 2;
            this.btnAccountRegister.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnAccountRegister.OnIdleState.ForeColor = System.Drawing.Color.SeaGreen;
            this.btnAccountRegister.OnIdleState.IconLeftImage = null;
            this.btnAccountRegister.OnIdleState.IconRightImage = null;
            this.btnAccountRegister.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAccountRegister.OnPressedState.BorderRadius = 35;
            this.btnAccountRegister.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccountRegister.OnPressedState.BorderThickness = 2;
            this.btnAccountRegister.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAccountRegister.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAccountRegister.OnPressedState.IconLeftImage = null;
            this.btnAccountRegister.OnPressedState.IconRightImage = null;
            this.btnAccountRegister.Size = new System.Drawing.Size(160, 49);
            this.btnAccountRegister.TabIndex = 9;
            this.btnAccountRegister.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAccountRegister.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAccountRegister.TextMarginLeft = 0;
            this.btnAccountRegister.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAccountRegister.UseDefaultRadiusAndThickness = true;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(119, 372);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(206, 13);
            this.label5.TabIndex = 8;
            this.label5.Text = "Tôi đã đọc và đồng ý với điều khoản trên";
            // 
            // linkPolicy
            // 
            this.linkPolicy.AutoSize = true;
            this.linkPolicy.Location = new System.Drawing.Point(93, 349);
            this.linkPolicy.Name = "linkPolicy";
            this.linkPolicy.Size = new System.Drawing.Size(103, 13);
            this.linkPolicy.TabIndex = 6;
            this.linkPolicy.TabStop = true;
            this.linkPolicy.Text = "Điều khoản sử dụng";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Arial", 21.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(149, 61);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(133, 34);
            this.label4.TabIndex = 0;
            this.label4.Text = "Đăng Ký";
            // 
            // chkPolicy
            // 
            this.chkPolicy.AllowBindingControlAnimation = true;
            this.chkPolicy.AllowBindingControlColorChanges = false;
            this.chkPolicy.AllowBindingControlLocation = true;
            this.chkPolicy.AllowCheckBoxAnimation = false;
            this.chkPolicy.AllowCheckmarkAnimation = true;
            this.chkPolicy.AllowOnHoverStates = true;
            this.chkPolicy.AutoCheck = true;
            this.chkPolicy.BackColor = System.Drawing.Color.Transparent;
            this.chkPolicy.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("chkPolicy.BackgroundImage")));
            this.chkPolicy.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.chkPolicy.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.chkPolicy.BorderRadius = 12;
            this.chkPolicy.Checked = false;
            this.chkPolicy.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Unchecked;
            this.chkPolicy.Cursor = System.Windows.Forms.Cursors.Default;
            this.chkPolicy.CustomCheckmarkImage = null;
            this.chkPolicy.Location = new System.Drawing.Point(96, 368);
            this.chkPolicy.MinimumSize = new System.Drawing.Size(17, 17);
            this.chkPolicy.Name = "chkPolicy";
            this.chkPolicy.OnCheck.BorderColor = System.Drawing.Color.DodgerBlue;
            this.chkPolicy.OnCheck.BorderRadius = 12;
            this.chkPolicy.OnCheck.BorderThickness = 2;
            this.chkPolicy.OnCheck.CheckBoxColor = System.Drawing.Color.DodgerBlue;
            this.chkPolicy.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.chkPolicy.OnCheck.CheckmarkThickness = 2;
            this.chkPolicy.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.chkPolicy.OnDisable.BorderRadius = 12;
            this.chkPolicy.OnDisable.BorderThickness = 2;
            this.chkPolicy.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkPolicy.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.chkPolicy.OnDisable.CheckmarkThickness = 2;
            this.chkPolicy.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkPolicy.OnHoverChecked.BorderRadius = 12;
            this.chkPolicy.OnHoverChecked.BorderThickness = 2;
            this.chkPolicy.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkPolicy.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.chkPolicy.OnHoverChecked.CheckmarkThickness = 2;
            this.chkPolicy.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkPolicy.OnHoverUnchecked.BorderRadius = 12;
            this.chkPolicy.OnHoverUnchecked.BorderThickness = 1;
            this.chkPolicy.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkPolicy.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.chkPolicy.OnUncheck.BorderRadius = 12;
            this.chkPolicy.OnUncheck.BorderThickness = 1;
            this.chkPolicy.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkPolicy.Size = new System.Drawing.Size(21, 21);
            this.chkPolicy.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.chkPolicy.TabIndex = 7;
            this.chkPolicy.ThreeState = false;
            this.chkPolicy.ToolTipText = null;
            // 
            // bunifuSeparator2
            // 
            this.bunifuSeparator2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator2.BackgroundImage")));
            this.bunifuSeparator2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator2.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator2.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator2.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator2.LineThickness = 1;
            this.bunifuSeparator2.Location = new System.Drawing.Point(68, 111);
            this.bunifuSeparator2.Name = "bunifuSeparator2";
            this.bunifuSeparator2.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator2.Size = new System.Drawing.Size(300, 14);
            this.bunifuSeparator2.TabIndex = 5;
            // 
            // txtRegisterPhoneNumber
            // 
            this.txtRegisterPhoneNumber.AcceptsReturn = false;
            this.txtRegisterPhoneNumber.AcceptsTab = false;
            this.txtRegisterPhoneNumber.AnimationSpeed = 200;
            this.txtRegisterPhoneNumber.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtRegisterPhoneNumber.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtRegisterPhoneNumber.BackColor = System.Drawing.Color.Transparent;
            this.txtRegisterPhoneNumber.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtRegisterPhoneNumber.BackgroundImage")));
            this.txtRegisterPhoneNumber.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtRegisterPhoneNumber.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtRegisterPhoneNumber.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtRegisterPhoneNumber.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtRegisterPhoneNumber.BorderRadius = 35;
            this.txtRegisterPhoneNumber.BorderThickness = 1;
            this.txtRegisterPhoneNumber.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtRegisterPhoneNumber.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRegisterPhoneNumber.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtRegisterPhoneNumber.DefaultText = "";
            this.txtRegisterPhoneNumber.FillColor = System.Drawing.Color.White;
            this.txtRegisterPhoneNumber.HideSelection = true;
            this.txtRegisterPhoneNumber.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtRegisterPhoneNumber.IconLeft")));
            this.txtRegisterPhoneNumber.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRegisterPhoneNumber.IconPadding = 4;
            this.txtRegisterPhoneNumber.IconRight = null;
            this.txtRegisterPhoneNumber.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRegisterPhoneNumber.Lines = new string[0];
            this.txtRegisterPhoneNumber.Location = new System.Drawing.Point(96, 294);
            this.txtRegisterPhoneNumber.MaxLength = 32767;
            this.txtRegisterPhoneNumber.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtRegisterPhoneNumber.Modified = false;
            this.txtRegisterPhoneNumber.Multiline = false;
            this.txtRegisterPhoneNumber.Name = "txtRegisterPhoneNumber";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegisterPhoneNumber.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtRegisterPhoneNumber.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegisterPhoneNumber.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegisterPhoneNumber.OnIdleState = stateProperties12;
            this.txtRegisterPhoneNumber.Padding = new System.Windows.Forms.Padding(3);
            this.txtRegisterPhoneNumber.PasswordChar = '\0';
            this.txtRegisterPhoneNumber.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtRegisterPhoneNumber.PlaceholderText = "Số điện thoại";
            this.txtRegisterPhoneNumber.ReadOnly = false;
            this.txtRegisterPhoneNumber.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtRegisterPhoneNumber.SelectedText = "";
            this.txtRegisterPhoneNumber.SelectionLength = 0;
            this.txtRegisterPhoneNumber.SelectionStart = 0;
            this.txtRegisterPhoneNumber.ShortcutsEnabled = true;
            this.txtRegisterPhoneNumber.Size = new System.Drawing.Size(260, 37);
            this.txtRegisterPhoneNumber.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtRegisterPhoneNumber.TabIndex = 4;
            this.txtRegisterPhoneNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtRegisterPhoneNumber.TextMarginBottom = 0;
            this.txtRegisterPhoneNumber.TextMarginLeft = 3;
            this.txtRegisterPhoneNumber.TextMarginTop = 0;
            this.txtRegisterPhoneNumber.TextPlaceholder = "Số điện thoại";
            this.txtRegisterPhoneNumber.UseSystemPasswordChar = false;
            this.txtRegisterPhoneNumber.WordWrap = true;
            // 
            // txtConfirmRegisterPassword
            // 
            this.txtConfirmRegisterPassword.AcceptsReturn = false;
            this.txtConfirmRegisterPassword.AcceptsTab = false;
            this.txtConfirmRegisterPassword.AnimationSpeed = 200;
            this.txtConfirmRegisterPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtConfirmRegisterPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtConfirmRegisterPassword.BackColor = System.Drawing.Color.Transparent;
            this.txtConfirmRegisterPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtConfirmRegisterPassword.BackgroundImage")));
            this.txtConfirmRegisterPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtConfirmRegisterPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtConfirmRegisterPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtConfirmRegisterPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtConfirmRegisterPassword.BorderRadius = 35;
            this.txtConfirmRegisterPassword.BorderThickness = 1;
            this.txtConfirmRegisterPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtConfirmRegisterPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtConfirmRegisterPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtConfirmRegisterPassword.DefaultText = "";
            this.txtConfirmRegisterPassword.FillColor = System.Drawing.Color.White;
            this.txtConfirmRegisterPassword.HideSelection = true;
            this.txtConfirmRegisterPassword.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtConfirmRegisterPassword.IconLeft")));
            this.txtConfirmRegisterPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtConfirmRegisterPassword.IconPadding = 4;
            this.txtConfirmRegisterPassword.IconRight = null;
            this.txtConfirmRegisterPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtConfirmRegisterPassword.Lines = new string[0];
            this.txtConfirmRegisterPassword.Location = new System.Drawing.Point(96, 237);
            this.txtConfirmRegisterPassword.MaxLength = 32767;
            this.txtConfirmRegisterPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtConfirmRegisterPassword.Modified = false;
            this.txtConfirmRegisterPassword.Multiline = false;
            this.txtConfirmRegisterPassword.Name = "txtConfirmRegisterPassword";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtConfirmRegisterPassword.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtConfirmRegisterPassword.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtConfirmRegisterPassword.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtConfirmRegisterPassword.OnIdleState = stateProperties16;
            this.txtConfirmRegisterPassword.Padding = new System.Windows.Forms.Padding(3);
            this.txtConfirmRegisterPassword.PasswordChar = '\0';
            this.txtConfirmRegisterPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtConfirmRegisterPassword.PlaceholderText = "Xác nhận mật khẩu";
            this.txtConfirmRegisterPassword.ReadOnly = false;
            this.txtConfirmRegisterPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtConfirmRegisterPassword.SelectedText = "";
            this.txtConfirmRegisterPassword.SelectionLength = 0;
            this.txtConfirmRegisterPassword.SelectionStart = 0;
            this.txtConfirmRegisterPassword.ShortcutsEnabled = true;
            this.txtConfirmRegisterPassword.Size = new System.Drawing.Size(260, 37);
            this.txtConfirmRegisterPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtConfirmRegisterPassword.TabIndex = 3;
            this.txtConfirmRegisterPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtConfirmRegisterPassword.TextMarginBottom = 0;
            this.txtConfirmRegisterPassword.TextMarginLeft = 3;
            this.txtConfirmRegisterPassword.TextMarginTop = 0;
            this.txtConfirmRegisterPassword.TextPlaceholder = "Xác nhận mật khẩu";
            this.txtConfirmRegisterPassword.UseSystemPasswordChar = false;
            this.txtConfirmRegisterPassword.WordWrap = true;
            // 
            // txtRegisterPassword
            // 
            this.txtRegisterPassword.AcceptsReturn = false;
            this.txtRegisterPassword.AcceptsTab = false;
            this.txtRegisterPassword.AnimationSpeed = 200;
            this.txtRegisterPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtRegisterPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtRegisterPassword.BackColor = System.Drawing.Color.Transparent;
            this.txtRegisterPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtRegisterPassword.BackgroundImage")));
            this.txtRegisterPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtRegisterPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtRegisterPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtRegisterPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtRegisterPassword.BorderRadius = 35;
            this.txtRegisterPassword.BorderThickness = 1;
            this.txtRegisterPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtRegisterPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRegisterPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtRegisterPassword.DefaultText = "";
            this.txtRegisterPassword.FillColor = System.Drawing.Color.White;
            this.txtRegisterPassword.HideSelection = true;
            this.txtRegisterPassword.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtRegisterPassword.IconLeft")));
            this.txtRegisterPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRegisterPassword.IconPadding = 4;
            this.txtRegisterPassword.IconRight = null;
            this.txtRegisterPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRegisterPassword.Lines = new string[0];
            this.txtRegisterPassword.Location = new System.Drawing.Point(96, 185);
            this.txtRegisterPassword.MaxLength = 32767;
            this.txtRegisterPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtRegisterPassword.Modified = false;
            this.txtRegisterPassword.Multiline = false;
            this.txtRegisterPassword.Name = "txtRegisterPassword";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegisterPassword.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtRegisterPassword.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegisterPassword.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegisterPassword.OnIdleState = stateProperties20;
            this.txtRegisterPassword.Padding = new System.Windows.Forms.Padding(3);
            this.txtRegisterPassword.PasswordChar = '\0';
            this.txtRegisterPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtRegisterPassword.PlaceholderText = "Mật khẩu";
            this.txtRegisterPassword.ReadOnly = false;
            this.txtRegisterPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtRegisterPassword.SelectedText = "";
            this.txtRegisterPassword.SelectionLength = 0;
            this.txtRegisterPassword.SelectionStart = 0;
            this.txtRegisterPassword.ShortcutsEnabled = true;
            this.txtRegisterPassword.Size = new System.Drawing.Size(260, 37);
            this.txtRegisterPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtRegisterPassword.TabIndex = 2;
            this.txtRegisterPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtRegisterPassword.TextMarginBottom = 0;
            this.txtRegisterPassword.TextMarginLeft = 3;
            this.txtRegisterPassword.TextMarginTop = 0;
            this.txtRegisterPassword.TextPlaceholder = "Mật khẩu";
            this.txtRegisterPassword.UseSystemPasswordChar = false;
            this.txtRegisterPassword.WordWrap = true;
            this.txtRegisterPassword.TextChanged += new System.EventHandler(this.bunifuTextBox4_TextChanged);
            // 
            // txtRegisterAccount
            // 
            this.txtRegisterAccount.AcceptsReturn = false;
            this.txtRegisterAccount.AcceptsTab = false;
            this.txtRegisterAccount.AnimationSpeed = 200;
            this.txtRegisterAccount.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtRegisterAccount.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtRegisterAccount.BackColor = System.Drawing.Color.Transparent;
            this.txtRegisterAccount.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtRegisterAccount.BackgroundImage")));
            this.txtRegisterAccount.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtRegisterAccount.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtRegisterAccount.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtRegisterAccount.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtRegisterAccount.BorderRadius = 35;
            this.txtRegisterAccount.BorderThickness = 1;
            this.txtRegisterAccount.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtRegisterAccount.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRegisterAccount.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtRegisterAccount.DefaultText = "";
            this.txtRegisterAccount.FillColor = System.Drawing.Color.White;
            this.txtRegisterAccount.HideSelection = true;
            this.txtRegisterAccount.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtRegisterAccount.IconLeft")));
            this.txtRegisterAccount.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRegisterAccount.IconPadding = 4;
            this.txtRegisterAccount.IconRight = null;
            this.txtRegisterAccount.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRegisterAccount.Lines = new string[0];
            this.txtRegisterAccount.Location = new System.Drawing.Point(96, 131);
            this.txtRegisterAccount.MaxLength = 32767;
            this.txtRegisterAccount.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtRegisterAccount.Modified = false;
            this.txtRegisterAccount.Multiline = false;
            this.txtRegisterAccount.Name = "txtRegisterAccount";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegisterAccount.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtRegisterAccount.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegisterAccount.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRegisterAccount.OnIdleState = stateProperties24;
            this.txtRegisterAccount.Padding = new System.Windows.Forms.Padding(3);
            this.txtRegisterAccount.PasswordChar = '\0';
            this.txtRegisterAccount.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtRegisterAccount.PlaceholderText = "Tài khoản";
            this.txtRegisterAccount.ReadOnly = false;
            this.txtRegisterAccount.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtRegisterAccount.SelectedText = "";
            this.txtRegisterAccount.SelectionLength = 0;
            this.txtRegisterAccount.SelectionStart = 0;
            this.txtRegisterAccount.ShortcutsEnabled = true;
            this.txtRegisterAccount.Size = new System.Drawing.Size(260, 37);
            this.txtRegisterAccount.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtRegisterAccount.TabIndex = 1;
            this.txtRegisterAccount.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtRegisterAccount.TextMarginBottom = 0;
            this.txtRegisterAccount.TextMarginLeft = 3;
            this.txtRegisterAccount.TextMarginTop = 0;
            this.txtRegisterAccount.TextPlaceholder = "Tài khoản";
            this.txtRegisterAccount.UseSystemPasswordChar = false;
            this.txtRegisterAccount.WordWrap = true;
            // 
            // errorProvider1
            // 
            this.errorProvider1.ContainerControl = this;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.SystemColors.Control;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.label6);
            this.bunifuGradientPanel1.Controls.Add(this.pictureBox2);
            this.bunifuGradientPanel1.Controls.Add(this.btnRegisterPage);
            this.bunifuGradientPanel1.Controls.Add(this.btnLoginPage);
            this.bunifuGradientPanel1.Controls.Add(this.pictureBox1);
            this.bunifuGradientPanel1.Controls.Add(this.label2);
            this.bunifuGradientPanel1.Controls.Add(this.label1);
            this.bunifuGradientPanel1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(172)))), ((int)(((byte)(136)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(193)))), ((int)(((byte)(149)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(173)))), ((int)(((byte)(164)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(173)))), ((int)(((byte)(164)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Margin = new System.Windows.Forms.Padding(2);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(401, 527);
            this.bunifuGradientPanel1.TabIndex = 0;
            this.bunifuGradientPanel1.Click += new System.EventHandler(this.bunifuGradientPanel1_Click);
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.Transparent;
            this.label6.Font = new System.Drawing.Font("Arial", 11.25F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.label6.Location = new System.Drawing.Point(127, 448);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(183, 17);
            this.label6.TabIndex = 5;
            this.label6.Text = "Copyright by codezooteam";
            // 
            // pictureBox2
            // 
            this.pictureBox2.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(96, 445);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(31, 24);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 4;
            this.pictureBox2.TabStop = false;
            // 
            // btnRegisterPage
            // 
            this.btnRegisterPage.AllowAnimations = true;
            this.btnRegisterPage.AllowMouseEffects = true;
            this.btnRegisterPage.AllowToggling = false;
            this.btnRegisterPage.AnimationSpeed = 200;
            this.btnRegisterPage.AutoGenerateColors = false;
            this.btnRegisterPage.AutoRoundBorders = false;
            this.btnRegisterPage.AutoSizeLeftIcon = true;
            this.btnRegisterPage.AutoSizeRightIcon = true;
            this.btnRegisterPage.BackColor = System.Drawing.Color.Transparent;
            this.btnRegisterPage.BackColor1 = System.Drawing.Color.Transparent;
            this.btnRegisterPage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRegisterPage.BackgroundImage")));
            this.btnRegisterPage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegisterPage.ButtonText = "ĐĂNG KÝ";
            this.btnRegisterPage.ButtonTextMarginLeft = 0;
            this.btnRegisterPage.ColorContrastOnClick = 45;
            this.btnRegisterPage.ColorContrastOnHover = 45;
            this.btnRegisterPage.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnRegisterPage.CustomizableEdges = borderEdges3;
            this.btnRegisterPage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRegisterPage.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRegisterPage.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRegisterPage.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRegisterPage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnRegisterPage.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnRegisterPage.ForeColor = System.Drawing.Color.White;
            this.btnRegisterPage.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRegisterPage.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRegisterPage.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRegisterPage.IconMarginLeft = 11;
            this.btnRegisterPage.IconPadding = 10;
            this.btnRegisterPage.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRegisterPage.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRegisterPage.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRegisterPage.IconSize = 25;
            this.btnRegisterPage.IdleBorderColor = System.Drawing.Color.White;
            this.btnRegisterPage.IdleBorderRadius = 35;
            this.btnRegisterPage.IdleBorderThickness = 2;
            this.btnRegisterPage.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnRegisterPage.IdleIconLeftImage = null;
            this.btnRegisterPage.IdleIconRightImage = null;
            this.btnRegisterPage.IndicateFocus = false;
            this.btnRegisterPage.Location = new System.Drawing.Point(205, 372);
            this.btnRegisterPage.Name = "btnRegisterPage";
            this.btnRegisterPage.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRegisterPage.OnDisabledState.BorderRadius = 35;
            this.btnRegisterPage.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegisterPage.OnDisabledState.BorderThickness = 2;
            this.btnRegisterPage.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRegisterPage.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRegisterPage.OnDisabledState.IconLeftImage = null;
            this.btnRegisterPage.OnDisabledState.IconRightImage = null;
            this.btnRegisterPage.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRegisterPage.onHoverState.BorderRadius = 35;
            this.btnRegisterPage.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegisterPage.onHoverState.BorderThickness = 2;
            this.btnRegisterPage.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRegisterPage.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnRegisterPage.onHoverState.IconLeftImage = null;
            this.btnRegisterPage.onHoverState.IconRightImage = null;
            this.btnRegisterPage.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnRegisterPage.OnIdleState.BorderRadius = 35;
            this.btnRegisterPage.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegisterPage.OnIdleState.BorderThickness = 2;
            this.btnRegisterPage.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnRegisterPage.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnRegisterPage.OnIdleState.IconLeftImage = null;
            this.btnRegisterPage.OnIdleState.IconRightImage = null;
            this.btnRegisterPage.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRegisterPage.OnPressedState.BorderRadius = 35;
            this.btnRegisterPage.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegisterPage.OnPressedState.BorderThickness = 2;
            this.btnRegisterPage.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRegisterPage.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnRegisterPage.OnPressedState.IconLeftImage = null;
            this.btnRegisterPage.OnPressedState.IconRightImage = null;
            this.btnRegisterPage.Size = new System.Drawing.Size(156, 43);
            this.btnRegisterPage.TabIndex = 3;
            this.btnRegisterPage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRegisterPage.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRegisterPage.TextMarginLeft = 0;
            this.btnRegisterPage.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnRegisterPage.UseDefaultRadiusAndThickness = true;
            this.btnRegisterPage.Click += new System.EventHandler(this.btnRegisterPage_Click);
            // 
            // btnLoginPage
            // 
            this.btnLoginPage.AllowAnimations = true;
            this.btnLoginPage.AllowMouseEffects = true;
            this.btnLoginPage.AllowToggling = false;
            this.btnLoginPage.AnimationSpeed = 200;
            this.btnLoginPage.AutoGenerateColors = false;
            this.btnLoginPage.AutoRoundBorders = false;
            this.btnLoginPage.AutoSizeLeftIcon = true;
            this.btnLoginPage.AutoSizeRightIcon = true;
            this.btnLoginPage.BackColor = System.Drawing.Color.Transparent;
            this.btnLoginPage.BackColor1 = System.Drawing.Color.Transparent;
            this.btnLoginPage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLoginPage.BackgroundImage")));
            this.btnLoginPage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoginPage.ButtonText = "ĐĂNG NHẬP";
            this.btnLoginPage.ButtonTextMarginLeft = 0;
            this.btnLoginPage.ColorContrastOnClick = 45;
            this.btnLoginPage.ColorContrastOnHover = 45;
            this.btnLoginPage.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnLoginPage.CustomizableEdges = borderEdges4;
            this.btnLoginPage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLoginPage.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLoginPage.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLoginPage.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLoginPage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLoginPage.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnLoginPage.ForeColor = System.Drawing.Color.White;
            this.btnLoginPage.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLoginPage.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLoginPage.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLoginPage.IconMarginLeft = 11;
            this.btnLoginPage.IconPadding = 10;
            this.btnLoginPage.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLoginPage.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLoginPage.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLoginPage.IconSize = 25;
            this.btnLoginPage.IdleBorderColor = System.Drawing.Color.White;
            this.btnLoginPage.IdleBorderRadius = 35;
            this.btnLoginPage.IdleBorderThickness = 2;
            this.btnLoginPage.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnLoginPage.IdleIconLeftImage = null;
            this.btnLoginPage.IdleIconRightImage = null;
            this.btnLoginPage.IndicateFocus = false;
            this.btnLoginPage.Location = new System.Drawing.Point(28, 372);
            this.btnLoginPage.Name = "btnLoginPage";
            this.btnLoginPage.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLoginPage.OnDisabledState.BorderRadius = 35;
            this.btnLoginPage.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoginPage.OnDisabledState.BorderThickness = 2;
            this.btnLoginPage.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLoginPage.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLoginPage.OnDisabledState.IconLeftImage = null;
            this.btnLoginPage.OnDisabledState.IconRightImage = null;
            this.btnLoginPage.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLoginPage.onHoverState.BorderRadius = 35;
            this.btnLoginPage.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoginPage.onHoverState.BorderThickness = 2;
            this.btnLoginPage.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLoginPage.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLoginPage.onHoverState.IconLeftImage = null;
            this.btnLoginPage.onHoverState.IconRightImage = null;
            this.btnLoginPage.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnLoginPage.OnIdleState.BorderRadius = 35;
            this.btnLoginPage.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoginPage.OnIdleState.BorderThickness = 2;
            this.btnLoginPage.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnLoginPage.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLoginPage.OnIdleState.IconLeftImage = null;
            this.btnLoginPage.OnIdleState.IconRightImage = null;
            this.btnLoginPage.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLoginPage.OnPressedState.BorderRadius = 35;
            this.btnLoginPage.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoginPage.OnPressedState.BorderThickness = 2;
            this.btnLoginPage.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLoginPage.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLoginPage.OnPressedState.IconLeftImage = null;
            this.btnLoginPage.OnPressedState.IconRightImage = null;
            this.btnLoginPage.Size = new System.Drawing.Size(156, 43);
            this.btnLoginPage.TabIndex = 2;
            this.btnLoginPage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLoginPage.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLoginPage.TextMarginLeft = 0;
            this.btnLoginPage.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLoginPage.UseDefaultRadiusAndThickness = true;
            this.btnLoginPage.Click += new System.EventHandler(this.btnLoginPage_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(134, 48);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(131, 100);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 1;
            this.pictureBox1.TabStop = false;
            // 
            // label2
            // 
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Arial", 15.75F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(74, 226);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(248, 109);
            this.label2.TabIndex = 0;
            this.label2.Text = "Phần mềm quản lý mật khẩu";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Arial", 21.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(128, 168);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(141, 34);
            this.label1.TabIndex = 0;
            this.label1.Text = "Xin Chào";
            // 
            // frmLoginandRegister
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(824, 527);
            this.Controls.Add(this.bunifuPages1);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "frmLoginandRegister";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Đăng nhập và Đăng ký";
            this.bunifuPages1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuGradientPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuPages bunifuPages1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLoginPage;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLoginAccount;
        private Bunifu.UI.WinForms.BunifuTextBox txtLoginPassword;
        private Bunifu.UI.WinForms.BunifuTextBox txtLoginAccount;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRegisterPage;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAccountRegister;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuCheckBox chkPolicy;
        private System.Windows.Forms.LinkLabel linkPolicy;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator2;
        private Bunifu.UI.WinForms.BunifuTextBox txtRegisterPhoneNumber;
        private Bunifu.UI.WinForms.BunifuTextBox txtConfirmRegisterPassword;
        private Bunifu.UI.WinForms.BunifuTextBox txtRegisterPassword;
        private Bunifu.UI.WinForms.BunifuTextBox txtRegisterAccount;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.LinkLabel linkForgotPassword;
        private System.Windows.Forms.ErrorProvider errorProvider1;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.PictureBox pictureBox2;
    }
}