namespace Password_Manager
{
    partial class frmOTP
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmOTP));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.txtOTP = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnConfirmOTP = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.txtMsg = new System.Windows.Forms.Label();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtPhone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtUsername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.otpMsg = new System.Windows.Forms.Label();
            this.ChangePswPanel = new Bunifu.UI.WinForms.BunifuPanel();
            this.label3 = new System.Windows.Forms.Label();
            this.btnChange = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtConfirmPsw = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNewPsw = new Bunifu.UI.WinForms.BunifuTextBox();
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            this.timer = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.btnResendOTP = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.bunifuPanel1.SuspendLayout();
            this.ChangePswPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // txtOTP
            // 
            this.txtOTP.AcceptsReturn = false;
            this.txtOTP.AcceptsTab = false;
            this.txtOTP.AnimationSpeed = 200;
            this.txtOTP.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtOTP.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtOTP.BackColor = System.Drawing.Color.Transparent;
            this.txtOTP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtOTP.BackgroundImage")));
            this.txtOTP.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtOTP.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtOTP.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtOTP.BorderColorIdle = System.Drawing.Color.LightGreen;
            this.txtOTP.BorderRadius = 35;
            this.txtOTP.BorderThickness = 1;
            this.txtOTP.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtOTP.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOTP.DefaultFont = new System.Drawing.Font("Arial", 9.75F, System.Drawing.FontStyle.Italic);
            this.txtOTP.DefaultText = "";
            this.txtOTP.FillColor = System.Drawing.Color.White;
            this.txtOTP.HideSelection = true;
            this.txtOTP.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtOTP.IconLeft")));
            this.txtOTP.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOTP.IconPadding = 10;
            this.txtOTP.IconRight = null;
            this.txtOTP.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOTP.Lines = new string[0];
            this.txtOTP.Location = new System.Drawing.Point(34, 120);
            this.txtOTP.MaxLength = 6;
            this.txtOTP.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtOTP.Modified = false;
            this.txtOTP.Multiline = false;
            this.txtOTP.Name = "txtOTP";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOTP.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtOTP.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOTP.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.LightGreen;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOTP.OnIdleState = stateProperties24;
            this.txtOTP.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtOTP.PasswordChar = '\0';
            this.txtOTP.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtOTP.PlaceholderText = "OTP";
            this.txtOTP.ReadOnly = false;
            this.txtOTP.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtOTP.SelectedText = "";
            this.txtOTP.SelectionLength = 0;
            this.txtOTP.SelectionStart = 0;
            this.txtOTP.ShortcutsEnabled = true;
            this.txtOTP.Size = new System.Drawing.Size(328, 43);
            this.txtOTP.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtOTP.TabIndex = 3;
            this.txtOTP.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtOTP.TextMarginBottom = 0;
            this.txtOTP.TextMarginLeft = 3;
            this.txtOTP.TextMarginTop = 0;
            this.txtOTP.TextPlaceholder = "OTP";
            this.txtOTP.UseSystemPasswordChar = false;
            this.txtOTP.WordWrap = true;
            // 
            // btnConfirmOTP
            // 
            this.btnConfirmOTP.AllowAnimations = true;
            this.btnConfirmOTP.AllowMouseEffects = true;
            this.btnConfirmOTP.AllowToggling = false;
            this.btnConfirmOTP.AnimationSpeed = 200;
            this.btnConfirmOTP.AutoGenerateColors = false;
            this.btnConfirmOTP.AutoRoundBorders = false;
            this.btnConfirmOTP.AutoSizeLeftIcon = true;
            this.btnConfirmOTP.AutoSizeRightIcon = true;
            this.btnConfirmOTP.BackColor = System.Drawing.Color.Transparent;
            this.btnConfirmOTP.BackColor1 = System.Drawing.Color.LightGreen;
            this.btnConfirmOTP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnConfirmOTP.BackgroundImage")));
            this.btnConfirmOTP.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfirmOTP.ButtonText = "Xác Nhận";
            this.btnConfirmOTP.ButtonTextMarginLeft = 0;
            this.btnConfirmOTP.ColorContrastOnClick = 45;
            this.btnConfirmOTP.ColorContrastOnHover = 45;
            this.btnConfirmOTP.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnConfirmOTP.CustomizableEdges = borderEdges5;
            this.btnConfirmOTP.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnConfirmOTP.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnConfirmOTP.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnConfirmOTP.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnConfirmOTP.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnConfirmOTP.Font = new System.Drawing.Font("Arial", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnConfirmOTP.ForeColor = System.Drawing.Color.Black;
            this.btnConfirmOTP.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnConfirmOTP.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnConfirmOTP.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnConfirmOTP.IconMarginLeft = 11;
            this.btnConfirmOTP.IconPadding = 10;
            this.btnConfirmOTP.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnConfirmOTP.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnConfirmOTP.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnConfirmOTP.IconSize = 25;
            this.btnConfirmOTP.IdleBorderColor = System.Drawing.Color.LightGreen;
            this.btnConfirmOTP.IdleBorderRadius = 35;
            this.btnConfirmOTP.IdleBorderThickness = 1;
            this.btnConfirmOTP.IdleFillColor = System.Drawing.Color.LightGreen;
            this.btnConfirmOTP.IdleIconLeftImage = null;
            this.btnConfirmOTP.IdleIconRightImage = null;
            this.btnConfirmOTP.IndicateFocus = false;
            this.btnConfirmOTP.Location = new System.Drawing.Point(127, 215);
            this.btnConfirmOTP.Name = "btnConfirmOTP";
            this.btnConfirmOTP.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnConfirmOTP.OnDisabledState.BorderRadius = 35;
            this.btnConfirmOTP.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfirmOTP.OnDisabledState.BorderThickness = 1;
            this.btnConfirmOTP.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnConfirmOTP.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnConfirmOTP.OnDisabledState.IconLeftImage = null;
            this.btnConfirmOTP.OnDisabledState.IconRightImage = null;
            this.btnConfirmOTP.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnConfirmOTP.onHoverState.BorderRadius = 35;
            this.btnConfirmOTP.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfirmOTP.onHoverState.BorderThickness = 1;
            this.btnConfirmOTP.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnConfirmOTP.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnConfirmOTP.onHoverState.IconLeftImage = null;
            this.btnConfirmOTP.onHoverState.IconRightImage = null;
            this.btnConfirmOTP.OnIdleState.BorderColor = System.Drawing.Color.LightGreen;
            this.btnConfirmOTP.OnIdleState.BorderRadius = 35;
            this.btnConfirmOTP.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfirmOTP.OnIdleState.BorderThickness = 1;
            this.btnConfirmOTP.OnIdleState.FillColor = System.Drawing.Color.LightGreen;
            this.btnConfirmOTP.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnConfirmOTP.OnIdleState.IconLeftImage = null;
            this.btnConfirmOTP.OnIdleState.IconRightImage = null;
            this.btnConfirmOTP.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnConfirmOTP.OnPressedState.BorderRadius = 35;
            this.btnConfirmOTP.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfirmOTP.OnPressedState.BorderThickness = 1;
            this.btnConfirmOTP.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnConfirmOTP.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnConfirmOTP.OnPressedState.IconLeftImage = null;
            this.btnConfirmOTP.OnPressedState.IconRightImage = null;
            this.btnConfirmOTP.Size = new System.Drawing.Size(150, 39);
            this.btnConfirmOTP.TabIndex = 4;
            this.btnConfirmOTP.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnConfirmOTP.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnConfirmOTP.TextMarginLeft = 0;
            this.btnConfirmOTP.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnConfirmOTP.UseDefaultRadiusAndThickness = true;
            this.btnConfirmOTP.Click += new System.EventHandler(this.btnConfirmOTP_Click);
            // 
            // errorProvider1
            // 
            this.errorProvider1.ContainerControl = this;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Arial", 21.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.LimeGreen;
            this.label1.Location = new System.Drawing.Point(159, 18);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(74, 34);
            this.label1.TabIndex = 1;
            this.label1.Text = "OTP";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Arial", 9.75F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(54, 68);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(284, 16);
            this.label2.TabIndex = 2;
            this.label2.Text = "Mã OTP đã được gửi đến số điện thoại của bạn";
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.txtMsg);
            this.bunifuPanel1.Controls.Add(this.bunifuButton1);
            this.bunifuPanel1.Controls.Add(this.txtPhone);
            this.bunifuPanel1.Controls.Add(this.txtUsername);
            this.bunifuPanel1.Location = new System.Drawing.Point(14, 14);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(372, 286);
            this.bunifuPanel1.TabIndex = 5;
            this.bunifuPanel1.VisibleChanged += new System.EventHandler(this.bunifuPanel1_VisibleChanged);
            // 
            // txtMsg
            // 
            this.txtMsg.AutoSize = true;
            this.txtMsg.Location = new System.Drawing.Point(161, 36);
            this.txtMsg.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.txtMsg.Name = "txtMsg";
            this.txtMsg.Size = new System.Drawing.Size(0, 13);
            this.txtMsg.TabIndex = 2;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Xác Nhận";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges6;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.LimeGreen;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.LimeGreen;
            this.bunifuButton1.IdleBorderRadius = 35;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(121, 211);
            this.bunifuButton1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 35;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 35;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.LimeGreen;
            this.bunifuButton1.OnIdleState.BorderRadius = 35;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.LimeGreen;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 35;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(127, 41);
            this.bunifuButton1.TabIndex = 1;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // txtPhone
            // 
            this.txtPhone.AcceptsReturn = false;
            this.txtPhone.AcceptsTab = false;
            this.txtPhone.AnimationSpeed = 200;
            this.txtPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPhone.BackColor = System.Drawing.Color.Transparent;
            this.txtPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPhone.BackgroundImage")));
            this.txtPhone.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPhone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPhone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPhone.BorderColorIdle = System.Drawing.Color.GreenYellow;
            this.txtPhone.BorderRadius = 35;
            this.txtPhone.BorderThickness = 1;
            this.txtPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPhone.DefaultText = "";
            this.txtPhone.FillColor = System.Drawing.Color.White;
            this.txtPhone.HideSelection = true;
            this.txtPhone.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtPhone.IconLeft")));
            this.txtPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.IconPadding = 10;
            this.txtPhone.IconRight = null;
            this.txtPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.Lines = new string[0];
            this.txtPhone.Location = new System.Drawing.Point(75, 139);
            this.txtPhone.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txtPhone.MaxLength = 32767;
            this.txtPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPhone.Modified = false;
            this.txtPhone.Multiline = false;
            this.txtPhone.Name = "txtPhone";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPhone.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.GreenYellow;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnIdleState = stateProperties28;
            this.txtPhone.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txtPhone.PasswordChar = '\0';
            this.txtPhone.PlaceholderForeColor = System.Drawing.Color.LightGreen;
            this.txtPhone.PlaceholderText = "Nhập số điện thoại";
            this.txtPhone.ReadOnly = false;
            this.txtPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPhone.SelectedText = "";
            this.txtPhone.SelectionLength = 0;
            this.txtPhone.SelectionStart = 0;
            this.txtPhone.ShortcutsEnabled = true;
            this.txtPhone.Size = new System.Drawing.Size(221, 47);
            this.txtPhone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPhone.TabIndex = 0;
            this.txtPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtPhone.TextMarginBottom = 0;
            this.txtPhone.TextMarginLeft = 3;
            this.txtPhone.TextMarginTop = 0;
            this.txtPhone.TextPlaceholder = "Nhập số điện thoại";
            this.txtPhone.UseSystemPasswordChar = false;
            this.txtPhone.WordWrap = true;
            this.txtPhone.TextChanged += new System.EventHandler(this.bunifuTextBox1_TextChanged);
            // 
            // txtUsername
            // 
            this.txtUsername.AcceptsReturn = false;
            this.txtUsername.AcceptsTab = false;
            this.txtUsername.AnimationSpeed = 200;
            this.txtUsername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUsername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUsername.BackColor = System.Drawing.Color.Transparent;
            this.txtUsername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUsername.BackgroundImage")));
            this.txtUsername.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUsername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUsername.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUsername.BorderColorIdle = System.Drawing.Color.GreenYellow;
            this.txtUsername.BorderRadius = 35;
            this.txtUsername.BorderThickness = 1;
            this.txtUsername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUsername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsername.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtUsername.DefaultText = "";
            this.txtUsername.FillColor = System.Drawing.Color.White;
            this.txtUsername.HideSelection = true;
            this.txtUsername.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtUsername.IconLeft")));
            this.txtUsername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsername.IconPadding = 10;
            this.txtUsername.IconRight = null;
            this.txtUsername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsername.Lines = new string[0];
            this.txtUsername.Location = new System.Drawing.Point(75, 64);
            this.txtUsername.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txtUsername.MaxLength = 32767;
            this.txtUsername.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUsername.Modified = false;
            this.txtUsername.Multiline = false;
            this.txtUsername.Name = "txtUsername";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsername.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUsername.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsername.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.GreenYellow;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsername.OnIdleState = stateProperties32;
            this.txtUsername.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txtUsername.PasswordChar = '\0';
            this.txtUsername.PlaceholderForeColor = System.Drawing.Color.LightGreen;
            this.txtUsername.PlaceholderText = "Nhập tài khoản";
            this.txtUsername.ReadOnly = false;
            this.txtUsername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUsername.SelectedText = "";
            this.txtUsername.SelectionLength = 0;
            this.txtUsername.SelectionStart = 0;
            this.txtUsername.ShortcutsEnabled = true;
            this.txtUsername.Size = new System.Drawing.Size(221, 47);
            this.txtUsername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUsername.TabIndex = 0;
            this.txtUsername.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtUsername.TextMarginBottom = 0;
            this.txtUsername.TextMarginLeft = 3;
            this.txtUsername.TextMarginTop = 0;
            this.txtUsername.TextPlaceholder = "Nhập tài khoản";
            this.txtUsername.UseSystemPasswordChar = false;
            this.txtUsername.WordWrap = true;
            this.txtUsername.TextChanged += new System.EventHandler(this.bunifuTextBox1_TextChanged);
            // 
            // otpMsg
            // 
            this.otpMsg.AutoSize = true;
            this.otpMsg.Location = new System.Drawing.Point(162, 98);
            this.otpMsg.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.otpMsg.Name = "otpMsg";
            this.otpMsg.Size = new System.Drawing.Size(0, 13);
            this.otpMsg.TabIndex = 6;
            // 
            // ChangePswPanel
            // 
            this.ChangePswPanel.BackgroundColor = System.Drawing.Color.Transparent;
            this.ChangePswPanel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ChangePswPanel.BackgroundImage")));
            this.ChangePswPanel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ChangePswPanel.BorderColor = System.Drawing.Color.Transparent;
            this.ChangePswPanel.BorderRadius = 3;
            this.ChangePswPanel.BorderThickness = 1;
            this.ChangePswPanel.Controls.Add(this.label3);
            this.ChangePswPanel.Controls.Add(this.btnChange);
            this.ChangePswPanel.Controls.Add(this.txtConfirmPsw);
            this.ChangePswPanel.Controls.Add(this.txtNewPsw);
            this.ChangePswPanel.Location = new System.Drawing.Point(11, 11);
            this.ChangePswPanel.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.ChangePswPanel.Name = "ChangePswPanel";
            this.ChangePswPanel.ShowBorders = true;
            this.ChangePswPanel.Size = new System.Drawing.Size(375, 290);
            this.ChangePswPanel.TabIndex = 5;
            this.ChangePswPanel.Visible = false;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(161, 36);
            this.label3.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(0, 13);
            this.label3.TabIndex = 2;
            // 
            // btnChange
            // 
            this.btnChange.AllowAnimations = true;
            this.btnChange.AllowMouseEffects = true;
            this.btnChange.AllowToggling = false;
            this.btnChange.AnimationSpeed = 200;
            this.btnChange.AutoGenerateColors = false;
            this.btnChange.AutoRoundBorders = false;
            this.btnChange.AutoSizeLeftIcon = true;
            this.btnChange.AutoSizeRightIcon = true;
            this.btnChange.BackColor = System.Drawing.Color.Transparent;
            this.btnChange.BackColor1 = System.Drawing.Color.Transparent;
            this.btnChange.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnChange.BackgroundImage")));
            this.btnChange.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChange.ButtonText = "Xác Nhận";
            this.btnChange.ButtonTextMarginLeft = 0;
            this.btnChange.ColorContrastOnClick = 45;
            this.btnChange.ColorContrastOnHover = 45;
            this.btnChange.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnChange.CustomizableEdges = borderEdges8;
            this.btnChange.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnChange.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChange.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChange.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChange.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnChange.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnChange.ForeColor = System.Drawing.Color.LimeGreen;
            this.btnChange.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChange.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnChange.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnChange.IconMarginLeft = 11;
            this.btnChange.IconPadding = 10;
            this.btnChange.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnChange.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnChange.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnChange.IconSize = 25;
            this.btnChange.IdleBorderColor = System.Drawing.Color.LimeGreen;
            this.btnChange.IdleBorderRadius = 35;
            this.btnChange.IdleBorderThickness = 1;
            this.btnChange.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnChange.IdleIconLeftImage = null;
            this.btnChange.IdleIconRightImage = null;
            this.btnChange.IndicateFocus = false;
            this.btnChange.Location = new System.Drawing.Point(121, 211);
            this.btnChange.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btnChange.Name = "btnChange";
            this.btnChange.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChange.OnDisabledState.BorderRadius = 35;
            this.btnChange.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChange.OnDisabledState.BorderThickness = 1;
            this.btnChange.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChange.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChange.OnDisabledState.IconLeftImage = null;
            this.btnChange.OnDisabledState.IconRightImage = null;
            this.btnChange.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnChange.onHoverState.BorderRadius = 35;
            this.btnChange.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChange.onHoverState.BorderThickness = 1;
            this.btnChange.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnChange.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnChange.onHoverState.IconLeftImage = null;
            this.btnChange.onHoverState.IconRightImage = null;
            this.btnChange.OnIdleState.BorderColor = System.Drawing.Color.LimeGreen;
            this.btnChange.OnIdleState.BorderRadius = 35;
            this.btnChange.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChange.OnIdleState.BorderThickness = 1;
            this.btnChange.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnChange.OnIdleState.ForeColor = System.Drawing.Color.LimeGreen;
            this.btnChange.OnIdleState.IconLeftImage = null;
            this.btnChange.OnIdleState.IconRightImage = null;
            this.btnChange.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChange.OnPressedState.BorderRadius = 35;
            this.btnChange.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChange.OnPressedState.BorderThickness = 1;
            this.btnChange.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChange.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnChange.OnPressedState.IconLeftImage = null;
            this.btnChange.OnPressedState.IconRightImage = null;
            this.btnChange.Size = new System.Drawing.Size(127, 41);
            this.btnChange.TabIndex = 1;
            this.btnChange.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnChange.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnChange.TextMarginLeft = 0;
            this.btnChange.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnChange.UseDefaultRadiusAndThickness = true;
            this.btnChange.Click += new System.EventHandler(this.btnChange_Click);
            // 
            // txtConfirmPsw
            // 
            this.txtConfirmPsw.AcceptsReturn = false;
            this.txtConfirmPsw.AcceptsTab = false;
            this.txtConfirmPsw.AnimationSpeed = 200;
            this.txtConfirmPsw.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtConfirmPsw.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtConfirmPsw.BackColor = System.Drawing.Color.Transparent;
            this.txtConfirmPsw.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtConfirmPsw.BackgroundImage")));
            this.txtConfirmPsw.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtConfirmPsw.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtConfirmPsw.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtConfirmPsw.BorderColorIdle = System.Drawing.Color.GreenYellow;
            this.txtConfirmPsw.BorderRadius = 35;
            this.txtConfirmPsw.BorderThickness = 1;
            this.txtConfirmPsw.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtConfirmPsw.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtConfirmPsw.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtConfirmPsw.DefaultText = "";
            this.txtConfirmPsw.FillColor = System.Drawing.Color.White;
            this.txtConfirmPsw.HideSelection = true;
            this.txtConfirmPsw.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtConfirmPsw.IconLeft")));
            this.txtConfirmPsw.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtConfirmPsw.IconPadding = 10;
            this.txtConfirmPsw.IconRight = null;
            this.txtConfirmPsw.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtConfirmPsw.Lines = new string[0];
            this.txtConfirmPsw.Location = new System.Drawing.Point(75, 139);
            this.txtConfirmPsw.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txtConfirmPsw.MaxLength = 32767;
            this.txtConfirmPsw.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtConfirmPsw.Modified = false;
            this.txtConfirmPsw.Multiline = false;
            this.txtConfirmPsw.Name = "txtConfirmPsw";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtConfirmPsw.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtConfirmPsw.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtConfirmPsw.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.GreenYellow;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtConfirmPsw.OnIdleState = stateProperties36;
            this.txtConfirmPsw.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txtConfirmPsw.PasswordChar = '\0';
            this.txtConfirmPsw.PlaceholderForeColor = System.Drawing.Color.LightGreen;
            this.txtConfirmPsw.PlaceholderText = "Xác nhận mật khẩu mới";
            this.txtConfirmPsw.ReadOnly = false;
            this.txtConfirmPsw.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtConfirmPsw.SelectedText = "";
            this.txtConfirmPsw.SelectionLength = 0;
            this.txtConfirmPsw.SelectionStart = 0;
            this.txtConfirmPsw.ShortcutsEnabled = true;
            this.txtConfirmPsw.Size = new System.Drawing.Size(221, 47);
            this.txtConfirmPsw.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtConfirmPsw.TabIndex = 0;
            this.txtConfirmPsw.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtConfirmPsw.TextMarginBottom = 0;
            this.txtConfirmPsw.TextMarginLeft = 3;
            this.txtConfirmPsw.TextMarginTop = 0;
            this.txtConfirmPsw.TextPlaceholder = "Xác nhận mật khẩu mới";
            this.txtConfirmPsw.UseSystemPasswordChar = false;
            this.txtConfirmPsw.WordWrap = true;
            this.txtConfirmPsw.TextChange += new System.EventHandler(this.txtConfirmPsw_TextChange);
            this.txtConfirmPsw.TextChanged += new System.EventHandler(this.bunifuTextBox1_TextChanged);
            this.txtConfirmPsw.Validating += new System.ComponentModel.CancelEventHandler(this.txtConfirmPsw_Validating);
            // 
            // txtNewPsw
            // 
            this.txtNewPsw.AcceptsReturn = false;
            this.txtNewPsw.AcceptsTab = false;
            this.txtNewPsw.AnimationSpeed = 200;
            this.txtNewPsw.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNewPsw.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNewPsw.BackColor = System.Drawing.Color.Transparent;
            this.txtNewPsw.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNewPsw.BackgroundImage")));
            this.txtNewPsw.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNewPsw.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNewPsw.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNewPsw.BorderColorIdle = System.Drawing.Color.GreenYellow;
            this.txtNewPsw.BorderRadius = 35;
            this.txtNewPsw.BorderThickness = 1;
            this.txtNewPsw.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNewPsw.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPsw.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNewPsw.DefaultText = "";
            this.txtNewPsw.FillColor = System.Drawing.Color.White;
            this.txtNewPsw.HideSelection = true;
            this.txtNewPsw.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtNewPsw.IconLeft")));
            this.txtNewPsw.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPsw.IconPadding = 10;
            this.txtNewPsw.IconRight = null;
            this.txtNewPsw.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPsw.Lines = new string[0];
            this.txtNewPsw.Location = new System.Drawing.Point(75, 62);
            this.txtNewPsw.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txtNewPsw.MaxLength = 32767;
            this.txtNewPsw.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNewPsw.Modified = false;
            this.txtNewPsw.Multiline = false;
            this.txtNewPsw.Name = "txtNewPsw";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPsw.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNewPsw.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPsw.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.GreenYellow;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPsw.OnIdleState = stateProperties40;
            this.txtNewPsw.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txtNewPsw.PasswordChar = '\0';
            this.txtNewPsw.PlaceholderForeColor = System.Drawing.Color.LightGreen;
            this.txtNewPsw.PlaceholderText = "Nhập mật khẩu mới";
            this.txtNewPsw.ReadOnly = false;
            this.txtNewPsw.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNewPsw.SelectedText = "";
            this.txtNewPsw.SelectionLength = 0;
            this.txtNewPsw.SelectionStart = 0;
            this.txtNewPsw.ShortcutsEnabled = true;
            this.txtNewPsw.Size = new System.Drawing.Size(221, 47);
            this.txtNewPsw.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNewPsw.TabIndex = 0;
            this.txtNewPsw.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtNewPsw.TextMarginBottom = 0;
            this.txtNewPsw.TextMarginLeft = 3;
            this.txtNewPsw.TextMarginTop = 0;
            this.txtNewPsw.TextPlaceholder = "Nhập mật khẩu mới";
            this.txtNewPsw.UseSystemPasswordChar = false;
            this.txtNewPsw.WordWrap = true;
            this.txtNewPsw.TextChange += new System.EventHandler(this.txtNewPsw_TextChange);
            this.txtNewPsw.TextChanged += new System.EventHandler(this.bunifuTextBox1_TextChanged);
            this.txtNewPsw.Validating += new System.ComponentModel.CancelEventHandler(this.txtNewPsw_Validating);
            // 
            // timer1
            // 
            this.timer1.Interval = 1000;
            this.timer1.Tick += new System.EventHandler(this.timer1_Tick);
            // 
            // timer
            // 
            this.timer.AutoSize = true;
            this.timer.Font = new System.Drawing.Font("Arial", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.timer.Location = new System.Drawing.Point(368, 138);
            this.timer.Name = "timer";
            this.timer.Size = new System.Drawing.Size(22, 16);
            this.timer.TabIndex = 7;
            this.timer.Text = "30";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Arial", 9.75F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(85, 171);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(134, 16);
            this.label4.TabIndex = 8;
            this.label4.Text = "Chưa nhận được mã?";
            // 
            // btnResendOTP
            // 
            this.btnResendOTP.AllowAnimations = true;
            this.btnResendOTP.AllowMouseEffects = true;
            this.btnResendOTP.AllowToggling = false;
            this.btnResendOTP.AnimationSpeed = 200;
            this.btnResendOTP.AutoGenerateColors = false;
            this.btnResendOTP.AutoRoundBorders = false;
            this.btnResendOTP.AutoSizeLeftIcon = true;
            this.btnResendOTP.AutoSizeRightIcon = true;
            this.btnResendOTP.BackColor = System.Drawing.Color.Transparent;
            this.btnResendOTP.BackColor1 = System.Drawing.Color.LightGreen;
            this.btnResendOTP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnResendOTP.BackgroundImage")));
            this.btnResendOTP.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnResendOTP.ButtonText = "Gửi lại";
            this.btnResendOTP.ButtonTextMarginLeft = 0;
            this.btnResendOTP.ColorContrastOnClick = 45;
            this.btnResendOTP.ColorContrastOnHover = 45;
            this.btnResendOTP.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnResendOTP.CustomizableEdges = borderEdges7;
            this.btnResendOTP.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnResendOTP.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnResendOTP.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnResendOTP.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnResendOTP.Enabled = false;
            this.btnResendOTP.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnResendOTP.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Bold);
            this.btnResendOTP.ForeColor = System.Drawing.Color.Black;
            this.btnResendOTP.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnResendOTP.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnResendOTP.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnResendOTP.IconMarginLeft = 11;
            this.btnResendOTP.IconPadding = 10;
            this.btnResendOTP.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnResendOTP.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnResendOTP.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnResendOTP.IconSize = 25;
            this.btnResendOTP.IdleBorderColor = System.Drawing.Color.LightGreen;
            this.btnResendOTP.IdleBorderRadius = 25;
            this.btnResendOTP.IdleBorderThickness = 1;
            this.btnResendOTP.IdleFillColor = System.Drawing.Color.LightGreen;
            this.btnResendOTP.IdleIconLeftImage = null;
            this.btnResendOTP.IdleIconRightImage = null;
            this.btnResendOTP.IndicateFocus = false;
            this.btnResendOTP.Location = new System.Drawing.Point(225, 169);
            this.btnResendOTP.Name = "btnResendOTP";
            this.btnResendOTP.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnResendOTP.OnDisabledState.BorderRadius = 25;
            this.btnResendOTP.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnResendOTP.OnDisabledState.BorderThickness = 1;
            this.btnResendOTP.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnResendOTP.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnResendOTP.OnDisabledState.IconLeftImage = null;
            this.btnResendOTP.OnDisabledState.IconRightImage = null;
            this.btnResendOTP.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnResendOTP.onHoverState.BorderRadius = 25;
            this.btnResendOTP.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnResendOTP.onHoverState.BorderThickness = 1;
            this.btnResendOTP.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnResendOTP.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnResendOTP.onHoverState.IconLeftImage = null;
            this.btnResendOTP.onHoverState.IconRightImage = null;
            this.btnResendOTP.OnIdleState.BorderColor = System.Drawing.Color.LightGreen;
            this.btnResendOTP.OnIdleState.BorderRadius = 25;
            this.btnResendOTP.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnResendOTP.OnIdleState.BorderThickness = 1;
            this.btnResendOTP.OnIdleState.FillColor = System.Drawing.Color.LightGreen;
            this.btnResendOTP.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnResendOTP.OnIdleState.IconLeftImage = null;
            this.btnResendOTP.OnIdleState.IconRightImage = null;
            this.btnResendOTP.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnResendOTP.OnPressedState.BorderRadius = 25;
            this.btnResendOTP.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnResendOTP.OnPressedState.BorderThickness = 1;
            this.btnResendOTP.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnResendOTP.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnResendOTP.OnPressedState.IconLeftImage = null;
            this.btnResendOTP.OnPressedState.IconRightImage = null;
            this.btnResendOTP.Size = new System.Drawing.Size(88, 27);
            this.btnResendOTP.TabIndex = 9;
            this.btnResendOTP.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnResendOTP.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnResendOTP.TextMarginLeft = 0;
            this.btnResendOTP.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnResendOTP.UseDefaultRadiusAndThickness = true;
            this.btnResendOTP.Click += new System.EventHandler(this.btnResendOTP_Click);
            // 
            // frmOTP
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(400, 320);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.ChangePswPanel);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.txtOTP);
            this.Controls.Add(this.otpMsg);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.btnConfirmOTP);
            this.Controls.Add(this.timer);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.btnResendOTP);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "frmOTP";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmOTP";
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.ChangePswPanel.ResumeLayout(false);
            this.ChangePswPanel.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuTextBox txtOTP;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnConfirmOTP;
        private System.Windows.Forms.ErrorProvider errorProvider1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuTextBox txtUsername;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuTextBox txtPhone;
        private System.Windows.Forms.Label txtMsg;
        private System.Windows.Forms.Label otpMsg;
        private Bunifu.UI.WinForms.BunifuPanel ChangePswPanel;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnChange;
        private Bunifu.UI.WinForms.BunifuTextBox txtConfirmPsw;
        private Bunifu.UI.WinForms.BunifuTextBox txtNewPsw;
        private System.Windows.Forms.Label timer;
        private System.Windows.Forms.Timer timer1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnResendOTP;
        private System.Windows.Forms.Label label4;
    }
}